services:
  nginx:
    image: nginx:1.9
    container_name: symfony-more-challenge.local
    volumes:
      # Mount source-code for development
      - ./:/app
      - ./docker/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "8062:80"
    restart: unless-stopped
    environment:
      - VIRTUAL_HOST=symfony-more-challenge.local
  php:
    build:
      context: ./docker
      args:
        GITHUB_TOKEN: ${GITHUB_TOKEN}
        MY_USERNAME: ${MY_USERNAME}
    container_name: symfony-more-challenge.local.fpm
    volumes:
      # Re-use local composer cache via host-volume
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      # Mount source-code for development
      - ./:/app:delegated
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
    restart: unless-stopped
    user: ${MY_UID}:${MY_GID}
  redis:
    image : redis:6.2
    container_name: symfony-more-challenge-redis
    expose:
      - 6379
    restart: unless-stopped
    volumes:
      - cache:/data
  mysql:
    image : mysql:8.0.34
    container_name: symfony-more-challenge-mysql
    volumes:
      - ./database:/var/lib/mysql
    ports:
      - 3306:3306
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${MYSQL_DB}
      MYSQL_USER: ${MYSQL_USR}
      MYSQL_PASSWORD: ${MYSQL_PWD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PWD}
volumes:
  cache:
    driver: local
networks:
  default:
    name: nginx-proxy
    external: true
