controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
app.swagger_ui:
    path: /api/doc
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }
oauth2:
    resource: '@LeagueOAuth2ServerBundle/Resources/config/routes.php'
    type: php
