@hostname = localhost
@port = 8062
@host = {{hostname}}:{{port}}
@contentType = application/json

### index
GET http://{{host}}/api/category HTTP/1.1

### show
GET http://{{host}}/api/category/22 HTTP/1.1

###
POST http://{{host}}/api/category HTTP/1.1
Content-Type: {{contentType}}

{
    "name": "Bag",
    "description": "Bag"
}

### update

PUT  http://{{host}}/api/category/141 HTTP/1.1
Content-Type: {{contentType}}

{
    "name": "yyy",
    "description": "xxxx"
}

### delete

DELETE  http://{{host}}/api/category/14 HTTP/1.1

