@hostname = localhost
@port = 8062
@host = {{hostname}}:{{port}}
@contentType = application/json

### index
GET http://{{host}}/api/product-attribute HTTP/1.1

### show
GET http://{{host}}/api/product-attribute/1 HTTP/1.1

###
POST http://{{host}}/api/product-attribute HTTP/1.1
Content-Type: {{contentType}}

{
    "product_id": 99,
    "attribute_id": 99
}

### update

PUT  http://{{host}}/api/product-attribute/1 HTTP/1.1
Content-Type: {{contentType}}

{
    "product_id": 88,
    "attribute_id": 88
}

### delete

DELETE  http://{{host}}/api/product-attribute/88 HTTP/1.1

