@hostname = localhost
@port = 8062
@host = {{hostname}}:{{port}}
@contentType = application/json

### index
GET http://{{host}}/api/user HTTP/1.1

### show
GET http://{{host}}/api/user/99 HTTP/1.1

###
POST http://{{host}}/api/user HTTP/1.1
Content-Type: {{contentType}}

{
    "email": "444@444.com",
    "password": "password",
    "name": "name",
    "phone": "name",
    "address": "address"
}

### update

PUT  http://{{host}}/api/user/1 HTTP/1.1
Content-Type: {{contentType}}

{
    "email": "user@user.com",
    "password": "passwordxxx",
    "name": "namexxx",
    "phone": "namexxx",
    "address": "addressxxx"
}

### delete

DELETE  http://{{host}}/api/user/14 HTTP/1.1

