@hostname = localhost
@port = 8062
@host = {{hostname}}:{{port}}
@contentType = application/json

### index

GET http://{{host}}/api/order HTTP/1.1

### show
GET http://{{host}}/api/order/13 HTTP/1.1

### array
POST http://{{host}}/api/order HTTP/1.1
Content-Type: {{contentType}}

{
    "user_id": 4,
    "products": [
        {
            "product_id": 13,
            "quantity": 2
        },
        {
            "product_id": 13,
            "quantity": 2
        },
        {
            "product_id": 13,
            "quantity": 2
        },
        {
            "product_id": 88,
            "quantity": 3
        }
    ]
}

### update

PUT  http://{{host}}/api/order/12 HTTP/1.1
Content-Type: {{contentType}}

{
    "status": "status"
}

### delete

DELETE  http://{{host}}/api/order/14 HTTP/1.1

